spring:
  config:
    import: optional:file:../.env.dev[.properties]
  docker:
    compose:
      enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: never
  ai:
    openai:
      api-key: ${AI_OPENAI_API_KEY}

app:
  auth:
    registration-mail:
      from: ${APP_AUTH_REGISTRATION_MAIL_FROM:no-reply@iabacus.co.kr}
      subject: ${APP_AUTH_REGISTRATION_MAIL_SUBJECT:[ABMS] 회원가입 링크 안내}
      confirm-url: ${APP_AUTH_REGISTRATION_MAIL_CONFIRM_URL:http://localhost:5173/auths/registration-confirm}

logging:
  level:
    p6spy: warn
