spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
  sql:
    init:
      mode: never
  ai:
    openai:
      api-key: ${AI_OPENAI_API_KEY}

logging:
  level:
    p6spy: warn
