-- 데모 데이터 보강: 직원 연락처·직무·기술·근무 형태·경력, 협력사 상세, 부서 소개 (가상 정보)

UPDATE `tb_employee` SET `phone` = '010-2001-7919', `job` = 'MANAGEMENT', `skills` = '인사·노무, 채용, 교육 기획', `work_type` = 'HYBRID', `career_start_date` = '2001-03-02' WHERE `id` = 1;
UPDATE `tb_employee` SET `phone` = '010-2002-5838', `job` = 'PROJECT_MANAGEMENT', `skills` = '제안서 작성, 사업 관리, 리스크 관리', `work_type` = 'HYBRID', `career_start_date` = '2004-06-03' WHERE `id` = 2;
UPDATE `tb_employee` SET `phone` = '010-2003-3757', `job` = 'PROJECT_MANAGEMENT', `skills` = '프로젝트 관리, 일정·원가 관리, PMP', `work_type` = 'CLIENT_SITE', `career_start_date` = '2006-01-22' WHERE `id` = 3;
UPDATE `tb_employee` SET `phone` = '010-2004-1676', `job` = 'PROJECT_MANAGEMENT', `skills` = '요구사항 정의, 이해관계자 관리, Jira', `work_type` = 'REMOTE', `career_start_date` = '2007-09-21' WHERE `id` = 4;
UPDATE `tb_employee` SET `phone` = '010-2005-9595', `job` = 'DEVELOPMENT', `skills` = 'Java, Spring Boot, JPA, MySQL', `work_type` = 'CLIENT_SITE', `career_start_date` = '2009-06-03' WHERE `id` = 5;
UPDATE `tb_employee` SET `phone` = '010-2006-7514', `job` = 'PROJECT_MANAGEMENT', `skills` = '프로젝트 관리, 일정·원가 관리, PMP', `work_type` = 'OFFICE', `career_start_date` = NULL WHERE `id` = 6;
UPDATE `tb_employee` SET `phone` = '010-2007-5433', `job` = 'PROJECT_MANAGEMENT', `skills` = '요구사항 정의, 이해관계자 관리, Jira', `work_type` = 'HYBRID', `career_start_date` = '2010-05-16' WHERE `id` = 7;
UPDATE `tb_employee` SET `phone` = '010-2008-3352', `job` = 'PROJECT_MANAGEMENT', `skills` = '제안서 작성, 사업 관리, 리스크 관리', `work_type` = 'CLIENT_SITE', `career_start_date` = '2008-10-26' WHERE `id` = 8;
UPDATE `tb_employee` SET `phone` = '010-2009-1271', `job` = 'PROJECT_MANAGEMENT', `skills` = '프로젝트 관리, 일정·원가 관리, PMP', `work_type` = 'REMOTE', `career_start_date` = NULL WHERE `id` = 9;
UPDATE `tb_employee` SET `phone` = '010-2010-9190', `job` = 'INFRA', `skills` = 'Linux, Docker, Jenkins, ArgoCD', `work_type` = 'CLIENT_SITE', `career_start_date` = '2012-05-11' WHERE `id` = 10;
UPDATE `tb_employee` SET `phone` = '010-2011-7109', `job` = 'CONSULTING', `skills` = 'PI, BPR, 업무 분석', `work_type` = 'HYBRID', `career_start_date` = '2012-02-05' WHERE `id` = 11;
UPDATE `tb_employee` SET `phone` = '010-2012-5028', `job` = 'PROJECT_MANAGEMENT', `skills` = '프로젝트 관리, 일정·원가 관리, PMP', `work_type` = 'HYBRID', `career_start_date` = NULL WHERE `id` = 12;
UPDATE `tb_employee` SET `phone` = '010-2013-2947', `job` = 'PROJECT_MANAGEMENT', `skills` = '요구사항 정의, 이해관계자 관리, Jira', `work_type` = 'CLIENT_SITE', `career_start_date` = '2012-07-04' WHERE `id` = 13;
UPDATE `tb_employee` SET `phone` = '010-2014-0866', `job` = 'PROJECT_MANAGEMENT', `skills` = '제안서 작성, 사업 관리, 리스크 관리', `work_type` = 'REMOTE', `career_start_date` = '2012-03-20' WHERE `id` = 14;
UPDATE `tb_employee` SET `phone` = '010-2015-8785', `job` = 'PROJECT_MANAGEMENT', `skills` = '프로젝트 관리, 일정·원가 관리, PMP', `work_type` = 'CLIENT_SITE', `career_start_date` = NULL WHERE `id` = 15;
UPDATE `tb_employee` SET `phone` = '010-2016-6704', `job` = 'PROJECT_MANAGEMENT', `skills` = '요구사항 정의, 이해관계자 관리, Jira', `work_type` = 'OFFICE', `career_start_date` = '2014-12-06' WHERE `id` = 16;
UPDATE `tb_employee` SET `phone` = '010-2017-4623', `job` = 'PROJECT_MANAGEMENT', `skills` = '제안서 작성, 사업 관리, 리스크 관리', `work_type` = 'HYBRID', `career_start_date` = '2013-04-21' WHERE `id` = 17;
UPDATE `tb_employee` SET `phone` = '010-2018-2542', `job` = 'PROJECT_MANAGEMENT', `skills` = '프로젝트 관리, 일정·원가 관리, PMP', `work_type` = 'CLIENT_SITE', `career_start_date` = NULL WHERE `id` = 18;
UPDATE `tb_employee` SET `phone` = '010-2019-0461', `job` = 'PROJECT_MANAGEMENT', `skills` = '요구사항 정의, 이해관계자 관리, Jira', `work_type` = 'REMOTE', `career_start_date` = '2013-02-10' WHERE `id` = 19;
UPDATE `tb_employee` SET `phone` = '010-2020-8380', `job` = 'PROJECT_MANAGEMENT', `skills` = '제안서 작성, 사업 관리, 리스크 관리', `work_type` = 'CLIENT_SITE', `career_start_date` = '2012-06-07' WHERE `id` = 20;
UPDATE `tb_employee` SET `phone` = '010-2021-6299', `job` = 'PROJECT_MANAGEMENT', `skills` = '프로젝트 관리, 일정·원가 관리, PMP', `work_type` = 'OFFICE', `career_start_date` = NULL WHERE `id` = 21;
UPDATE `tb_employee` SET `phone` = '010-2022-4218', `job` = 'PROJECT_MANAGEMENT', `skills` = '요구사항 정의, 이해관계자 관리, Jira', `work_type` = 'HYBRID', `career_start_date` = '2013-11-05' WHERE `id` = 22;
UPDATE `tb_employee` SET `phone` = '010-2023-2137', `job` = 'PROJECT_MANAGEMENT', `skills` = '제안서 작성, 사업 관리, 리스크 관리', `work_type` = 'CLIENT_SITE', `career_start_date` = '2013-03-11' WHERE `id` = 23;
UPDATE `tb_employee` SET `phone` = '010-2024-0056', `job` = 'DATA', `skills` = 'Python, Spark, Airflow, SQL', `work_type` = 'REMOTE', `career_start_date` = NULL WHERE `id` = 24;
UPDATE `tb_employee` SET `phone` = '010-2025-7975', `job` = 'INFRA', `skills` = 'Linux, Docker, Jenkins, ArgoCD', `work_type` = 'CLIENT_SITE', `career_start_date` = '2016-01-02' WHERE `id` = 25;
UPDATE `tb_employee` SET `phone` = '010-2026-5894', `job` = 'INFRA', `skills` = '네트워크, 보안, 모니터링(Prometheus)', `work_type` = 'OFFICE', `career_start_date` = '2019-12-24' WHERE `id` = 26;
UPDATE `tb_employee` SET `phone` = '010-2027-3813', `job` = 'INFRA', `skills` = 'AWS, Kubernetes, Terraform', `work_type` = 'HYBRID', `career_start_date` = NULL WHERE `id` = 27;
UPDATE `tb_employee` SET `phone` = '010-2028-1732', `job` = 'CONSULTING', `skills` = 'IT 전략 컨설팅, ISP, 프로세스 혁신', `work_type` = 'OFFICE', `career_start_date` = '2016-09-01' WHERE `id` = 28;
UPDATE `tb_employee` SET `phone` = '010-2029-9651', `job` = 'CONSULTING', `skills` = 'PI, BPR, 업무 분석', `work_type` = 'HYBRID', `career_start_date` = '2021-10-12' WHERE `id` = 29;
UPDATE `tb_employee` SET `phone` = '010-2030-7570', `job` = 'DEVELOPMENT', `skills` = 'Java, Spring Boot, JPA, MySQL', `work_type` = 'CLIENT_SITE', `career_start_date` = NULL WHERE `id` = 30;
UPDATE `tb_employee` SET `phone` = '010-2031-5489', `job` = 'DEVELOPMENT', `skills` = 'Kotlin, Spring, Redis, Kafka', `work_type` = 'OFFICE', `career_start_date` = '2021-01-20' WHERE `id` = 31;
UPDATE `tb_employee` SET `phone` = '010-2032-3408', `job` = 'DEVELOPMENT', `skills` = 'TypeScript, React, Node.js', `work_type` = 'HYBRID', `career_start_date` = '2020-06-08' WHERE `id` = 32;
UPDATE `tb_employee` SET `phone` = '010-2033-1327', `job` = 'DEVELOPMENT', `skills` = 'Java, Oracle, MyBatis, 전자정부프레임워크', `work_type` = 'CLIENT_SITE', `career_start_date` = NULL WHERE `id` = 33;
UPDATE `tb_employee` SET `phone` = '010-2034-9246', `job` = 'DEVELOPMENT', `skills` = 'Python, FastAPI, PostgreSQL', `work_type` = 'REMOTE', `career_start_date` = '2021-01-09' WHERE `id` = 34;
UPDATE `tb_employee` SET `phone` = '010-2035-7165', `job` = 'DEVELOPMENT', `skills` = 'Java, Spring Boot, JPA, MySQL', `work_type` = 'CLIENT_SITE', `career_start_date` = '2021-06-06' WHERE `id` = 35;
UPDATE `tb_employee` SET `phone` = '010-2036-5084', `job` = 'DEVELOPMENT', `skills` = 'Kotlin, Spring, Redis, Kafka', `work_type` = 'OFFICE', `career_start_date` = NULL WHERE `id` = 36;
UPDATE `tb_employee` SET `phone` = '010-2037-3003', `job` = 'DEVELOPMENT', `skills` = 'TypeScript, React, Node.js', `work_type` = 'HYBRID', `career_start_date` = '2024-05-02' WHERE `id` = 37;
UPDATE `tb_employee` SET `phone` = '010-2038-0922', `job` = 'DEVELOPMENT', `skills` = 'Java, Oracle, MyBatis, 전자정부프레임워크', `work_type` = 'CLIENT_SITE', `career_start_date` = '2014-12-14' WHERE `id` = 38;
UPDATE `tb_employee` SET `phone` = '010-2039-8841', `job` = 'DEVELOPMENT', `skills` = 'Python, FastAPI, PostgreSQL', `work_type` = 'REMOTE', `career_start_date` = NULL WHERE `id` = 39;
UPDATE `tb_employee` SET `phone` = '010-2040-6760', `job` = 'DEVELOPMENT', `skills` = 'Java, Spring Boot, JPA, MySQL', `work_type` = 'CLIENT_SITE', `career_start_date` = '2022-05-08' WHERE `id` = 40;
UPDATE `tb_employee` SET `phone` = '010-2041-4679', `job` = 'DEVELOPMENT', `skills` = 'Kotlin, Spring, Redis, Kafka', `work_type` = 'OFFICE', `career_start_date` = '2015-08-20' WHERE `id` = 41;
UPDATE `tb_employee` SET `phone` = '010-2042-2598', `job` = 'DEVELOPMENT', `skills` = 'TypeScript, React, Node.js', `work_type` = 'HYBRID', `career_start_date` = NULL WHERE `id` = 42;
UPDATE `tb_employee` SET `phone` = '010-2043-0517', `job` = 'DEVELOPMENT', `skills` = 'Java, Oracle, MyBatis, 전자정부프레임워크', `work_type` = 'CLIENT_SITE', `career_start_date` = '2022-08-23' WHERE `id` = 43;
UPDATE `tb_employee` SET `phone` = '010-2044-8436', `job` = 'DEVELOPMENT', `skills` = 'Python, FastAPI, PostgreSQL', `work_type` = 'REMOTE', `career_start_date` = '2018-02-09' WHERE `id` = 44;
UPDATE `tb_employee` SET `phone` = '010-2045-6355', `job` = 'DEVELOPMENT', `skills` = 'Java, Spring Boot, JPA, MySQL', `work_type` = 'CLIENT_SITE', `career_start_date` = NULL WHERE `id` = 45;
UPDATE `tb_employee` SET `phone` = '010-2046-4274', `job` = 'DEVELOPMENT', `skills` = 'Kotlin, Spring, Redis, Kafka', `work_type` = 'OFFICE', `career_start_date` = '2022-03-10' WHERE `id` = 46;
UPDATE `tb_employee` SET `phone` = '010-2047-2193', `job` = 'DESIGN', `skills` = '퍼블리싱, HTML/CSS, 접근성', `work_type` = 'HYBRID', `career_start_date` = '2019-02-16' WHERE `id` = 47;
UPDATE `tb_employee` SET `phone` = '010-2048-0112', `job` = 'DEVELOPMENT', `skills` = 'Java, Oracle, MyBatis, 전자정부프레임워크', `work_type` = 'CLIENT_SITE', `career_start_date` = NULL WHERE `id` = 48;
UPDATE `tb_employee` SET `phone` = '010-2049-8031', `job` = 'DEVELOPMENT', `skills` = 'Python, FastAPI, PostgreSQL', `work_type` = 'REMOTE', `career_start_date` = '2019-10-23' WHERE `id` = 49;
UPDATE `tb_employee` SET `phone` = '010-2050-5950', `job` = 'DEVELOPMENT', `skills` = 'Java, Spring Boot, JPA, MySQL', `work_type` = 'CLIENT_SITE', `career_start_date` = '2023-03-27' WHERE `id` = 50;
UPDATE `tb_employee` SET `phone` = '010-2051-3869', `job` = 'DEVELOPMENT', `skills` = 'Kotlin, Spring, Redis, Kafka', `work_type` = 'OFFICE', `career_start_date` = NULL WHERE `id` = 51;
UPDATE `tb_employee` SET `phone` = '010-2052-1788', `job` = 'DEVELOPMENT', `skills` = 'TypeScript, React, Node.js', `work_type` = 'HYBRID', `career_start_date` = '2021-08-18' WHERE `id` = 52;
UPDATE `tb_employee` SET `phone` = '010-2053-9707', `job` = 'DEVELOPMENT', `skills` = 'Java, Oracle, MyBatis, 전자정부프레임워크', `work_type` = 'CLIENT_SITE', `career_start_date` = '2016-08-21' WHERE `id` = 53;
UPDATE `tb_employee` SET `phone` = '010-2054-7626', `job` = 'DEVELOPMENT', `skills` = 'Python, FastAPI, PostgreSQL', `work_type` = 'REMOTE', `career_start_date` = NULL WHERE `id` = 54;
UPDATE `tb_employee` SET `phone` = '010-2055-5545', `job` = 'DEVELOPMENT', `skills` = 'Java, Spring Boot, JPA, MySQL', `work_type` = 'CLIENT_SITE', `career_start_date` = '2019-07-17' WHERE `id` = 55;
UPDATE `tb_employee` SET `phone` = '010-2056-3464', `job` = 'MANAGEMENT', `skills` = '재무·회계, 원가 분석, ERP', `work_type` = 'OFFICE', `career_start_date` = '2016-12-06' WHERE `id` = 56;
UPDATE `tb_employee` SET `phone` = '010-2057-1383', `job` = 'MANAGEMENT', `skills` = '인사·노무, 채용, 교육 기획', `work_type` = 'HYBRID', `career_start_date` = NULL WHERE `id` = 57;
UPDATE `tb_employee` SET `phone` = '010-2058-9302', `job` = 'DEVELOPMENT', `skills` = 'Java, Oracle, MyBatis, 전자정부프레임워크', `work_type` = 'CLIENT_SITE', `career_start_date` = '2022-02-01' WHERE `id` = 58;
UPDATE `tb_employee` SET `phone` = '010-2059-7221', `job` = 'DEVELOPMENT', `skills` = 'Python, FastAPI, PostgreSQL', `work_type` = 'REMOTE', `career_start_date` = '2018-04-01' WHERE `id` = 59;
UPDATE `tb_employee` SET `phone` = '010-2060-5140', `job` = 'DEVELOPMENT', `skills` = 'Java, Spring Boot, JPA, MySQL', `work_type` = 'CLIENT_SITE', `career_start_date` = '2023-08-01' WHERE `id` = 60;
UPDATE `tb_employee` SET `phone` = '010-2061-3059', `job` = 'DEVELOPMENT', `skills` = 'Kotlin, Spring, Redis, Kafka', `work_type` = 'OFFICE', `career_start_date` = '2021-10-03' WHERE `id` = 61;
UPDATE `tb_employee` SET `phone` = '010-2062-0978', `job` = 'SALES', `skills` = '기술 영업, 제안 PT, 고객 관리', `work_type` = 'OFFICE', `career_start_date` = '2016-03-05' WHERE `id` = 62;

UPDATE `tb_party` SET `party_type` = 'CLIENT', `business_number` = '120-88-12345', `industry` = '클라우드·SaaS', `phone` = '02-6000-1001', `address` = '서울특별시 중구 세종대로 110', `website` = 'https://hanbit-cloud.example', `memo` = 'AI·클라우드 전환 사업 주요 고객사. 연간 유지보수 계약 협의 중.' WHERE `id` = 1;
UPDATE `tb_party` SET `party_type` = 'BOTH', `business_number` = '214-88-23456', `industry` = '시스템 통합(SI)', `phone` = '02-6000-1002', `address` = '경기도 성남시 분당구 판교역로 235', `website` = 'https://nuri-systems.example', `memo` = '데이터 플랫폼 공동 수행 파트너이자 고객사.' WHERE `id` = 2;
UPDATE `tb_party` SET `party_type` = 'CLIENT', `business_number` = '105-88-34567', `industry` = '금융·핀테크', `phone` = '02-6000-1003', `address` = '서울특별시 영등포구 국제금융로 10', `website` = 'https://daon-fintech.example', `memo` = '결제 시스템 고도화 발주처. 보안 심사 절차가 엄격함.' WHERE `id` = 3;
UPDATE `tb_party` SET `party_type` = 'CLIENT', `business_number` = '116-88-45678', `industry` = '통신', `phone` = '02-6000-1004', `address` = '서울특별시 종로구 종로 33', `website` = 'https://saesol-telecom.example', `memo` = '빌링·NMS 장기 거래 고객사.' WHERE `id` = 4;
UPDATE `tb_party` SET `party_type` = 'PARTNER', `business_number` = '312-88-56789', `industry` = '물류·IoT', `phone` = '031-600-1005', `address` = '인천광역시 연수구 송도과학로 32', `website` = 'https://mirae-logis.example', `memo` = 'IoT 관제 PoC 협력사. 디바이스 공급 담당.' WHERE `id` = 5;
UPDATE `tb_party` SET `party_type` = 'CLIENT', `business_number` = '220-88-67890', `industry` = '이커머스', `phone` = '02-6000-1006', `address` = '서울특별시 강남구 테헤란로 427', `website` = 'https://ongyeol.example', `memo` = '모바일 커머스·CRM 재구축 고객사.' WHERE `id` = 6;

UPDATE `tb_department` SET `description` = 'SI·SM 전문 기업. 공공·금융·통신 분야 시스템 구축과 운영을 수행합니다.' WHERE `id` = 1;
UPDATE `tb_department` SET `description` = '전사 경영 계획, 재무·원가 관리, 인사·총무를 담당합니다.' WHERE `id` = 2;
UPDATE `tb_department` SET `description` = '통신사업본부 산하 사업부를 총괄하며 사업 수주와 수행 품질을 책임집니다.' WHERE `id` = 3;
UPDATE `tb_department` SET `description` = '미래사업본부 산하 사업부를 총괄하며 사업 수주와 수행 품질을 책임집니다.' WHERE `id` = 4;
UPDATE `tb_department` SET `description` = '연구개발본부 산하 사업부를 총괄하며 사업 수주와 수행 품질을 책임집니다.' WHERE `id` = 5;
UPDATE `tb_department` SET `description` = '공통 플랫폼과 신기술 연구, 기술 표준 수립을 담당합니다.' WHERE `id` = 6;
UPDATE `tb_department` SET `description` = '전략사업담당 소속 팀의 사업 운영과 인력 배치를 조정합니다.' WHERE `id` = 7;
UPDATE `tb_department` SET `description` = 'AI/Data사업담당 소속 팀의 사업 운영과 인력 배치를 조정합니다.' WHERE `id` = 8;
UPDATE `tb_department` SET `description` = '통신이행담당 소속 팀의 사업 운영과 인력 배치를 조정합니다.' WHERE `id` = 9;
UPDATE `tb_department` SET `description` = '경영빌링담당 소속 팀의 사업 운영과 인력 배치를 조정합니다.' WHERE `id` = 10;
UPDATE `tb_department` SET `description` = '공통 플랫폼과 신기술 연구, 기술 표준 수립을 담당합니다.' WHERE `id` = 100;
UPDATE `tb_department` SET `description` = '컨버전스사업팀 관련 시스템 구축과 운영을 수행합니다.' WHERE `id` = 101;
UPDATE `tb_department` SET `description` = '금융·결제 시스템 구축과 보안 인증 대응을 수행합니다.' WHERE `id` = 102;
UPDATE `tb_department` SET `description` = 'IoT융합사업팀 관련 시스템 구축과 운영을 수행합니다.' WHERE `id` = 103;
UPDATE `tb_department` SET `description` = '융합서비스사업팀 관련 시스템 구축과 운영을 수행합니다.' WHERE `id` = 104;
UPDATE `tb_department` SET `description` = 'Data플랫폼사업팀 관련 시스템 구축과 운영을 수행합니다.' WHERE `id` = 105;
UPDATE `tb_department` SET `description` = '지능플랫폼사업팀 관련 시스템 구축과 운영을 수행합니다.' WHERE `id` = 106;
UPDATE `tb_department` SET `description` = 'Data서비스운영팀 관련 시스템 구축과 운영을 수행합니다.' WHERE `id` = 107;
UPDATE `tb_department` SET `description` = 'AI 서비스·LLM 기반 솔루션 개발과 고객사 AI 전환을 수행합니다.' WHERE `id` = 108;
UPDATE `tb_department` SET `description` = '서비스 기획, UX 리서치, UI 디자인과 퍼블리싱을 담당합니다.' WHERE `id` = 109;
UPDATE `tb_department` SET `description` = '고객정보 시스템 구축·고도화와 운영(SM)을 수행합니다.' WHERE `id` = 110;
UPDATE `tb_department` SET `description` = '가입정보 시스템 구축·고도화와 운영(SM)을 수행합니다.' WHERE `id` = 111;
UPDATE `tb_department` SET `description` = '빌링시스템 시스템 구축·고도화와 운영(SM)을 수행합니다.' WHERE `id` = 112;
UPDATE `tb_department` SET `description` = '영업정보 시스템 구축·고도화와 운영(SM)을 수행합니다.' WHERE `id` = 113;
UPDATE `tb_department` SET `description` = '클라우드·온프레미스 인프라 설계와 운영, DevOps를 담당합니다.' WHERE `id` = 114;
UPDATE `tb_department` SET `description` = '경영플랫폼팀 관련 시스템 구축과 운영을 수행합니다.' WHERE `id` = 115;
UPDATE `tb_department` SET `description` = 'CRM 시스템 구축·고도화와 운영(SM)을 수행합니다.' WHERE `id` = 116;
UPDATE `tb_department` SET `description` = '경영정보 시스템 구축·고도화와 운영(SM)을 수행합니다.' WHERE `id` = 117;
UPDATE `tb_department` SET `description` = 'NMS사업 시스템 구축·고도화와 운영(SM)을 수행합니다.' WHERE `id` = 118;
UPDATE `tb_department` SET `description` = '데이터 플랫폼 구축, 분석 모델 개발, 데이터 운영을 담당합니다.' WHERE `id` = 119;
