services:
  mysql:
    image: 'mysql:8.4'
    environment:
      - 'MYSQL_DATABASE=abms'
      - 'MYSQL_USER=abms'
      - 'MYSQL_PASSWORD=abms'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'TZ=Asia/Seoul'
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - '3308:3306'
