name: 작업 이슈
description: 기능/버그/리팩토링/잡무 이슈를 표준 형식으로 등록합니다.
title: "[type] "
body:
  - type: markdown
    attributes:
      value: |
        이 템플릿은 1~2일 단위 작업을 기준으로 합니다.
        생성 후 라벨을 아래 규칙대로 반드시 지정하세요.
        - type/* 1개: type/feature, type/bug, type/refactor, type/chore
        - priority/* 1개: priority/P0, priority/P1, priority/P2

  - type: dropdown
    id: issue_type
    attributes:
      label: 작업 유형
      description: 라벨 type/* 와 동일하게 선택하세요.
      options:
        - feature
        - bug
        - refactor
        - chore
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      description: 라벨 priority/* 와 동일하게 선택하세요.
      options:
        - P0 (24시간 내 착수)
        - P1 (이번 주 처리)
        - P2 (여유 슬롯 처리)
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 작업 요약
      description: 무엇을 왜 하는지 3~5줄로 작성하세요.
      placeholder: |
        예) 직원 검색에서 부서 필터를 추가합니다.
        데모 시나리오에서 검색 정확도를 높이기 위한 작업입니다.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 완료 조건 (Acceptance Criteria)
      description: 체크 가능한 조건으로 작성하세요.
      placeholder: |
        - [ ] 부서 필터로 검색 결과가 제한된다.
        - [ ] 관련 테스트가 추가/수정되었다.
        - [ ] 문서 영향이 있으면 반영했다.
    validations:
      required: true
